export const ALL_SALON_REQUEST = 'ALL_SALON_REQUEST'
export const ALL_SALON_SUCCESS = 'ALL_SALON_SUCCESS'
export const ALL_SALON_FAIL = 'ALL_SALON_FAIL'

export const ADMIN_SALON_REQUEST = 'ADMIN_SALON_REQUEST'
export const ADMIN_SALON_SUCCESS = 'ADMIN_SALON_SUCCESS'
export const ADMIN_SALON_FAIL = 'ADMIN_SALON_FAIL'




export const NEW_SALON_REQUEST = 'NEW_SALON_REQUEST'
export const NEW_SALON_SUCCESS = 'NEW_SALON_SUCCESS'
export const NEW_SALON_RESET = 'NEW_SALON_RESET'
export const NEW_SALON_FAIL = 'NEW_SALON_FAIL'

export const CLEAR_ERRORS = "CLEAR_ERRORS"









































// export const ADMIN_SALON_DETAILS_REQUEST = 'ADMIN_SALON_DETAILS_REQUEST'
// export const ADMIN_SALON_DETAILS_SUCCESS = 'ADMIN_SALON_DETAILS_SUCCESS'
// export const ADMIN_SALON_DETAILS_FAIL = 'ADMIN_SALON_DETAILS_FAIL'

// export const UPDATE_SALON_REQUEST = 'UPDATE_SALON_REQUEST'
// export const UPDATE_SALON_SUCCESS = 'UPDATE_SALON_SUCCESS'
// export const UPDATE_SALON_RESET = 'UPDATE_SALON_RESET'
// export const UPDATE_SALON_FAIL = 'UPDATE_SALON_FAIL'

// export const DELETE_SALON_REQUEST = 'DELETE_SALON_REQUEST'
// export const DELETE_SALON_SUCCESS = 'DELETE_SALON_SUCCESS'
// export const DELETE_SALON_RESET = 'DELETE_SALON_RESET'
// export const DELETE_SALON_FAIL = 'UPDATE_SALON_FAIL'